import type {
  NewProjectSubmission,
  VersionUpgradeSubmission,
  ProjectEstimationSubmission,
  ProjectApprovalSubmission,
  ProjectDeliverySubmission,
  ProjectFeedbackSubmission,
} from '@/lib/types';

export const sheetCsvConfigs = {
  newProjectSubmissions: {
    headers: [
      'Timestamp',
      'Email Address',
      'Project Name',
      'Client Name',
      'Company Name',
      'Company Type',
      'Project Description',
      'Client Message',
      'Client Country',
      'Client Timezone',
      'Communication Platforms',
      'Business Manager',
      'Internal Instructions',
      'Attachments',
      'Normalized Name',
      'Gdrive Folder Link',
    ],
    mapRow: (row: NewProjectSubmission) => ({
      'Timestamp': row.timestamp,
      'Email Address': row.emailAddress ?? '',
      'Project Name': row.projectName ?? '',
      'Client Name': row.clientName ?? '',
      'Company Name': row.companyName ?? '',
      'Company Type': row.companyType ?? '',
      'Project Description': row.projectDescription ?? '',
      'Client Message': row.clientMessage ?? '',
      'Client Country': row.clientCountry ?? '',
      'Client Timezone': row.clientTimezone ?? '',
      'Communication Platforms': row.communicationPlatforms ?? '',
      'Business Manager': row.businessManager ?? '',
      'Internal Instructions': row.internalInstructions ?? '',
      'Attachments': row.attachments ?? '',
      'Normalized Name': row.projectId ?? '',
      'Gdrive Folder Link': row.gdriveFolderLink ?? '',
    }),
  },
  versionUpgradeSubmissions: {
    headers: [
      'Timestamp',
      'Versionized Project Name',
      'Version',
      'New Requirements',
    ],
    mapRow: (row: VersionUpgradeSubmission) => ({
      'Timestamp': row.timestamp,
      'Versionized Project Name': row.projectId ?? '',
      'Version': row.version ?? '',
      'New Requirements': row.newRequirements ?? '',
    }),
  },
  projectEstimationSubmissions: {
    headers: [
      'Timestamp',
      'Project Name - Client Name',
      'Estimated Hours',
      'Estimated Cost',
    ],
    mapRow: (row: ProjectEstimationSubmission) => ({
      'Timestamp': row.timestamp,
      'Project Name - Client Name': row.projectId ?? '',
      'Estimated Hours': row.estimatedHours ?? '',
      'Estimated Cost': row.estimatedCost ?? '',
    }),
  },
  projectApprovalSubmissions: {
    headers: [
      'Timestamp',
      'Project Name',
      'Approved By',
      'Approval Date',
      'Expected Delivery Date',
      'Delivery Method',
    ],
    mapRow: (row: ProjectApprovalSubmission) => ({
      'Timestamp': row.timestamp,
      'Project Name': row.projectId ?? '',
      'Approved By': row.approvedBy ?? '',
      'Approval Date': row.approvalDate ?? '',
      'Expected Delivery Date': row.expectedDeliveryDate ?? '',
      'Delivery Method': row.deliveryMethod ?? '',
    }),
  },
  projectDeliverySubmissions: {
    headers: [
      'Timestamp',
      'Project Name',
      'Delivery Date',
      'Delivered By',
      'Notes',
    ],
    mapRow: (row: ProjectDeliverySubmission) => ({
      'Timestamp': row.timestamp,
      'Project Name': row.projectId ?? '',
      'Delivery Date': row.deliveryDate ?? '',
      'Delivered By': row.deliveredBy ?? '',
      'Notes': row.notes ?? '',
    }),
  },
  projectFeedbackSubmissions: {
    headers: [
      'Timestamp',
      'Project Name',
      'Satisfaction Score (1-5)',
      'Feedback',
      'Client Contact',
    ],
    mapRow: (row: ProjectFeedbackSubmission) => ({
      'Timestamp': row.timestamp,
      'Project Name': row.projectId ?? '',
      'Satisfaction Score (1-5)': row.satisfactionScore ?? '',
      'Feedback': row.feedback ?? '',
      'Client Contact': row.clientContact ?? '',
    }),
  },
} as const;
